name: Pull Request

on: pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.repository == 'augustoyuudi/potaku'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Run pnpm install on Root
        run: pnpm install
        working-directory: .
      - name: Danger
        run: pnpm danger ci --use-github-checks --failOnErrors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
